EE-6645: Update mule-file-connector version to 1.2.2-SNAPSHOT to avoid errors of NoClassDefFoundError: javax/activation/MimetypesFileTypeMap with JDK11 (#17)
(cherry picked from commit f40d630b7a85008e4fdbe86cb17d9d1b5188479e)